# Generated by Django 3.2.16 on 2023-01-19 12:17

from django.db import migrations
import drf_attachments.models.fields
import drf_attachments.storage


class Migration(migrations.Migration):

    dependencies = [
        ('drf_attachments', '0002_attachment_object_id_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=drf_attachments.models.fields.DynamicStorageFileField(storage=drf_attachments.storage.AttachmentFileStorage(), upload_to=drf_attachments.storage.attachment_upload_path, verbose_name='file'),
        ),
    ]
