# Generated by Django 2.2.24 on 2021-07-08 13:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rtr_zrdb.attachments.models.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Attachment ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('context', models.CharField(blank=True, help_text="Additional info about the attachment's context/meaning.", max_length=255, verbose_name='context')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(help_text='Additional info about the attachment (e.g. file meta data: mime_type, extension, size).', verbose_name='meta')),
                ('file', models.FileField(upload_to=rtr_zrdb.attachments.models.models.attachment_upload_path, verbose_name='file')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ('creation_date',),
            },
        ),
    ]
